title: Verena Thackeray
email: studio@verenathackeray.com
description: >- # this means to ignore newlines until "baseurl:"
  Art and movement coaching by Verena Thackeray.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://verenathackeray.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: davethackeray
github_username:  davethackeray

# Build settings
remote_theme: "davethackeray/mmistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache
